package main

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"tailscale.com/ipn/ipnstate"
	"tailscale.com/net/tsaddr"
)

// pacInputs is what the PAC script depends on, extracted from status
// and config so the script can be generated and compared cheaply.
type pacInputs struct {
	ProxyAddr  string   // host:port
	AllTraffic bool     // send everything through the proxy
	DNSSuffix  string   // MagicDNS suffix such as "example.ts.net", without dots around it
	Routes     []string // IPv4 subnet routes advertised by peers, CIDR
}

// pacInputsFrom derives the PAC inputs from the node's status. With
// an exit node selected, everything goes through the proxy; the
// config's PACAllTraffic does the same without one.
func pacInputsFrom(st *ipnstate.Status, cfg *Config, proxyAddr string) pacInputs {
	in := pacInputs{ProxyAddr: proxyAddr, AllTraffic: cfg.PACAllTraffic}
	if st == nil {
		return in
	}
	if st.ExitNodeStatus != nil {
		in.AllTraffic = true
	}
	in.DNSSuffix = strings.Trim(st.MagicDNSSuffix, ".")
	seen := map[string]bool{}
	for _, p := range st.Peer {
		if p.PrimaryRoutes == nil {
			continue
		}
		for _, r := range p.PrimaryRoutes.All() {
			if !r.Addr().Is4() || r.Bits() == 0 || tsaddr.IsTailscaleIP(r.Addr()) {
				continue
			}
			s := r.Masked().String()
			if !seen[s] {
				seen[s] = true
				in.Routes = append(in.Routes, s)
			}
		}
	}
	sort.Strings(in.Routes)
	return in
}

// pacScript renders the proxy auto-config script. It never resolves
// hostnames: the IP checks only run on IP literals, so browsing
// stays fast and nothing leaks to DNS from inside the script.
func pacScript(in pacInputs) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by tswipoexp. Proxy: %s\n", in.ProxyAddr)
	fmt.Fprintf(&b, "var P = \"PROXY %s\";\n", in.ProxyAddr)
	b.WriteString(`var D = "DIRECT";
function isV4(h) { return /^\d{1,3}(\.\d{1,3}){3}$/.test(h); }
function FindProxyForURL(url, host) {
  host = host.toLowerCase();
  if (host == "localhost" || host == "localhost.localdomain" || host == "127.0.0.1" || host == "::1" || host == "[::1]" ||
      /^127\./.test(host) || shExpMatch(host, "*.localhost")) {
    return D;
  }
`)
	if in.AllTraffic {
		b.WriteString("  return P;\n}\n")
		return b.String()
	}
	// Tailscale IPv4 range 100.64.0.0/10 and the IPv6 ULA prefix.
	b.WriteString(`  if (isV4(host) && isInNet(host, "100.64.0.0", "255.192.0.0")) return P;
  if (/^\[?fd7a:115c:a1e0:/.test(host)) return P;
  if (isPlainHostName(host)) return P;
`)
	if in.DNSSuffix != "" {
		// Both forms, since at least one PAC evaluator (.NET's, via
		// WinHTTP) was seen ignoring dnsDomainIs here.
		fmt.Fprintf(&b, "  if (dnsDomainIs(host, %q) || shExpMatch(host, %q) || host == %q) return P;\n", "."+in.DNSSuffix, "*."+in.DNSSuffix, in.DNSSuffix)
	}
	for _, r := range in.Routes {
		p, err := netip.ParsePrefix(r)
		if err != nil {
			continue
		}
		fmt.Fprintf(&b, "  if (isV4(host) && isInNet(host, %q, %q)) return P;\n", p.Masked().Addr().String(), v4Mask(p.Bits()))
	}
	b.WriteString("  return D;\n}\n")
	return b.String()
}

// v4Mask returns the dotted netmask for a prefix length.
func v4Mask(bits int) string {
	m := ^uint32(0) << (32 - bits)
	if bits == 0 {
		m = 0
	}
	return fmt.Sprintf("%d.%d.%d.%d", byte(m>>24), byte(m>>16), byte(m>>8), byte(m))
}
